export * from './user.controller'
export * from './marca.controller'
export * from './categoria.controller'
export * from './producto.controller'
export * from './cliente.controller'
export * from './proveedor.controller'