export * from './user.interface'
export * from './marca.interface'
export * from './categoria.interface'
export * from './producto.interface'
export * from './cliente.interface'
export * from './proveedor.interface'
